version: '3.7'

services:
    server:
        build:
            context: ./backend
            dockerfile: Dockerfile
            args:
                - DOCKER_ENV=${DOCKER_ENV:-prod}
        expose:
            - ${APP_SERVER_PORT}
        image: myapp-server
        container_name: myapp-node-server
        volumes:
            - ./backend/server:/usr/app/server
        ports:
            - ${APP_SERVER_PORT}:${APP_SERVER_PORT}
        environment:
            - DOCKER_ENV=${DOCKER_ENV:-prod}
            - APP_SERVER_PORT=${APP_SERVER_PORT}
        networks:
            - app-network
    client:
        build:
            context: ./frontend/project-x
            dockerfile: Dockerfile
        expose:
            - ${APP_CLIENT_PORT}
        image: myapp-client
        container_name: myapp-react-client
        volumes:
            - ./frontend/project-x/src:/usr/app/src
            - ./frontend/project-x/public:/usr/app/public
        depends_on:
            - server
        ports:
            - ${APP_CLIENT_PORT}:${APP_CLIENT_PORT}
        networks:
            - app-network
        stdin_open: true
        tty: true

networks:
    app-network:
        driver: bridge

