### Get all shop products
GET http://localhost:4001/shop

### Get single shop product
GET http://localhost:4001/shop/3

### Get all cart items
GET http://localhost:4001/cart

### Get single cart item
GET http://localhost:4001/cart/1

### Post shop product to cart
POST http://localhost:4001/cart/add/
content-type: application/json

{
    "id": "3",
    "comment": "I like that very much :-)"
}

### Update comment on cart item
PUT http://localhost:4001/cart/1
content-type: application/json

{
    "comment": "Or maybe not so much :("
}

### Remove item from cart
DELETE http://localhost:4001/cart/1